# {{ cookiecutter.project_name }} Jupyter Book Configuration

title: "{{ cookiecutter.project_name }}"
author: "{{ cookiecutter.full_name }}"
repository:
  url: "https://{{ cookiecutter.repo_name|replace('.', '') }}.readthedocs.io/"
  path_to_book: "docs/"

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - autoapi.extension

  config:
    autoapi_dirs: ["../src"]
    napoleon_google_docstring: True
    napoleon_numpy_docstring: False
    autodoc_typehints: "description"
